### ISSUE TITLE
Find images

### ISSUE THREAD

**Issue by sarahwylie** [nicnolen/Hawker#11]
What are the product categories that we need to seed the database? Sarah can find the images, but need to know the categories!

Images for: 
-Product categories

1.  Lawn/Garden/Outdoor
2. Transportation
3. Tech
4. Time
5.

**Comment by Sammychvz17** [comment]
> What are the product categories that we need to seed the database? Sarah can find the images, but need to know the categories!
> 
> 
> 
> Images for: 
> 
> -Product categories
> 
> 
> 
> 1.  Lawn/Garden/Outdoor
> 
> 2. Transportation
> 
> 3. Tech
> 
> 4. Time
> 
> 5. 


Hey! I think these categories could be good 

I update your list a little 





> 1.  Lawn/Garden/Outdoor
> 
> 2. Auto
> 
> 3. Tech
> 
> 4. Home / home decor
> 
> 5. Clothing 


Let's keep it pretty vast and simple!

**Comment by sarahwylie** [comment]
I created pages for:

- Homepage
- Auto
- Clothing
- Household
- Outdoor
- Tech

I created them and exported them, but I haven't written any code in them yet. Just FYI.

**Comment by JideOgun** [comment]
looks good.
